learning_users/basic_app/urls.py
from django.conf.urls import url 
from basic_app import views 

#TEMPLATE URLS

app_name = 'basic_app'

urlpatterns=[ 
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    #create relationship (dont inherit from user!)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # add any aditional attributes you want

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self):
        # built in attribute of django.contrib.auth.models.User!
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
   

    # class Meta():
    #     model = UserProfileInfo
    #     exclude = ('user',)

    #kopinta

    class Meta():
       model = User
       fields = ('username','email','password')
    
# class UserProfileInfoForm(forms.ModelForm):
#      class Meta():
#          fields = ('portfolio_site', 'profile_pics')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse 
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponsePermanentRedirect, HttpResponseRedirect, HttpResponse 
from django.contrib.auth import authenticate, login, logout 

# from django import forms
# from django.contrib.auth.models import User
from basic_app.forms import UserProfileInfoForm, UserForm

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')
@login_required
def user_logout(request):
    logout(request)
    return HttpResponsePermanentRedirect(reverse('index'))

def special(request):
    return HttpResponse("you are logged in, nice!")





def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get ('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("someone tied to login and failed")
            print("username {} and password {}".format(username, password))
            return HttpResponse("invalid login details suplied")
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



</head>
<body>
    <nav class = 'navbar navbar-default navbar-static-top'>
        <div class = 'container'>
<ul class="nav navbar-nav">
    <li><a class="navbar-brand" href="{% url 'index' %}"">Django</a></li>
    <li><a class="navbar-link" href="{% url 'admin:index' %}"">Admin</a></li>
    <li><a class="navbar-link" href="{% url 'basic_app:register' %}"">Register</a></li>
{% if user.is_authenticated %}
<li><a class='navbar-link' href="{% url 'logout' %}">LOGOUT</a></li>
{% else %}
<li><a class = 'navbar-link' href="{% url 'basic_app:user_login' %}">Login</a></li>
{% endif %}
</ul>
        </div>

    </nav>
<div class='container'>
    {% block body_block %}
    {% endblock %}

</div>


</body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
<h1>Django level five</h1>

</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="container">
<h1>Please login</h1>
<form action="{% url 'basic_app:user_login' %}" method="post">
{% csrf_token %}
<label for="username">Username</label>
<input type="text" name = "username" placeholder = "Enter Username">
<input type="password" name="password" id="">
<input type="submit" value="Login">
</form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
{% if registered %}
<h1>Thank you for registering</h1>
{% else %}
<h1>Register here</h1>
<h3>Fill out the form</h3>

<form action="" method="post" enctype = "multipart/form-data">
{% csrf_token %} 
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" value="Register">

</form>
{% endif %}
</div>


{% endblock %}